server.port=8081
spring.application.name=E-commerce
spring.datasource.url=jdbc:mysql://localhost:3306/mrm_handcraft
spring.datasource.username=root
spring.datasource.password=Meena@982002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
